const db = require("../../models");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");

const ResetPassword = async (req, res) => {
  try {
    const { token, newPassword } = req.body;

    if (!token) {
      return res.status(400).json({
        success: false,
        message: "Reset token is required",
      });
    }

    if (!newPassword) {
      return res.status(400).json({
        success: false,
        message: "Password is required",
      });
    }

    let decoded;
    try {
      decoded = jwt.verify(token, process.env.JWT_ACCESS_TOKEN || "defaultsecret");
    } catch (err) {
      return res.status(400).json({
        success: false,
        message: "Invalid or expired reset token",
      });
    }

    const user = await db.Users.findOne({
      where: {
        user_email: decoded.email,
      },
    });

    if (!user) {
      return res.status(404).json({
        success: false,
        message: "User not exists",
      });
    }

    let hashedPassword = await bcrypt.hash(newPassword, 10);
    
    // PHP Laravel compatibility: replace $2b$ prefix generated by Node.js bcrypt with $2y$
    if (hashedPassword.startsWith("$2b$")) {
      hashedPassword = hashedPassword.replace("$2b$", "$2y$");
    }

    await user.update({
      user_pass: hashedPassword,
    });

    return res.status(200).json({
      success: true,
      message: "Password reset successful",
      data: {},
    });
  } catch (error) {
    console.log("Error:", error);
    return res.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
};

module.exports = ResetPassword;
